# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: georesolver.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='georesolver.proto',
  package='stabox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11georesolver.proto\x12\x06stabox\x1a\x1cgoogle/api/annotations.proto\"$\n\x0eGetLocationReq\x12\x12\n\nip_address\x18\x01 \x01(\t\":\n\x0bGeoLocation\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0c\n\x04gray\x18\x03 \x01(\x08\x32t\n\x0bGeoResolver\x12\x65\n\x0bGetLocation\x12\x16.stabox.GetLocationReq\x1a\x13.stabox.GeoLocation\")\x82\xd3\xe4\x93\x02#\x12!/ip_address/{ip_address}/locationb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_GETLOCATIONREQ = _descriptor.Descriptor(
  name='GetLocationReq',
  full_name='stabox.GetLocationReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_address', full_name='stabox.GetLocationReq.ip_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=95,
)


_GEOLOCATION = _descriptor.Descriptor(
  name='GeoLocation',
  full_name='stabox.GeoLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='country', full_name='stabox.GeoLocation.country', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='stabox.GeoLocation.city', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gray', full_name='stabox.GeoLocation.gray', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['GetLocationReq'] = _GETLOCATIONREQ
DESCRIPTOR.message_types_by_name['GeoLocation'] = _GEOLOCATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetLocationReq = _reflection.GeneratedProtocolMessageType('GetLocationReq', (_message.Message,), {
  'DESCRIPTOR' : _GETLOCATIONREQ,
  '__module__' : 'georesolver_pb2'
  # @@protoc_insertion_point(class_scope:stabox.GetLocationReq)
  })
_sym_db.RegisterMessage(GetLocationReq)

GeoLocation = _reflection.GeneratedProtocolMessageType('GeoLocation', (_message.Message,), {
  'DESCRIPTOR' : _GEOLOCATION,
  '__module__' : 'georesolver_pb2'
  # @@protoc_insertion_point(class_scope:stabox.GeoLocation)
  })
_sym_db.RegisterMessage(GeoLocation)



_GEORESOLVER = _descriptor.ServiceDescriptor(
  name='GeoResolver',
  full_name='stabox.GeoResolver',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=157,
  serialized_end=273,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLocation',
    full_name='stabox.GeoResolver.GetLocation',
    index=0,
    containing_service=None,
    input_type=_GETLOCATIONREQ,
    output_type=_GEOLOCATION,
    serialized_options=_b('\202\323\344\223\002#\022!/ip_address/{ip_address}/location'),
  ),
])
_sym_db.RegisterServiceDescriptor(_GEORESOLVER)

DESCRIPTOR.services_by_name['GeoResolver'] = _GEORESOLVER

# @@protoc_insertion_point(module_scope)
