# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import georesolver_pb2 as georesolver__pb2


class GeoResolverStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetLocation = channel.unary_unary(
        '/stabox.GeoResolver/GetLocation',
        request_serializer=georesolver__pb2.GetLocationReq.SerializeToString,
        response_deserializer=georesolver__pb2.GeoLocation.FromString,
        )


class GeoResolverServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetLocation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GeoResolverServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetLocation': grpc.unary_unary_rpc_method_handler(
          servicer.GetLocation,
          request_deserializer=georesolver__pb2.GetLocationReq.FromString,
          response_serializer=georesolver__pb2.GeoLocation.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'stabox.GeoResolver', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
