# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import movies_pb2 as movies__pb2


class MoviesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getFileInfo = channel.unary_unary(
        '/stabox.Movies/getFileInfo',
        request_serializer=movies__pb2.MovieFile.SerializeToString,
        response_deserializer=movies__pb2.MovieFile.FromString,
        )


class MoviesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getFileInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MoviesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getFileInfo': grpc.unary_unary_rpc_method_handler(
          servicer.getFileInfo,
          request_deserializer=movies__pb2.MovieFile.FromString,
          response_serializer=movies__pb2.MovieFile.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'stabox.Movies', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
