# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movies.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='movies.proto',
  package='stabox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cmovies.proto\x12\x06stabox\"a\n\tMovieFile\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x02 \x01(\r\x12\x10\n\x08movie_id\x18\x03 \x01(\r\x12\x10\n\x08\x66ilename\x18\x04 \x01(\t\x12\x12\n\nservice_id\x18\x05 \x01(\r2?\n\x06Movies\x12\x35\n\x0bgetFileInfo\x12\x11.stabox.MovieFile\x1a\x11.stabox.MovieFile\"\x00\x62\x06proto3')
)




_MOVIEFILE = _descriptor.Descriptor(
  name='MovieFile',
  full_name='stabox.MovieFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_id', full_name='stabox.MovieFile._id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_id', full_name='stabox.MovieFile.file_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='movie_id', full_name='stabox.MovieFile.movie_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='stabox.MovieFile.filename', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_id', full_name='stabox.MovieFile.service_id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['MovieFile'] = _MOVIEFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MovieFile = _reflection.GeneratedProtocolMessageType('MovieFile', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEFILE,
  '__module__' : 'movies_pb2'
  # @@protoc_insertion_point(class_scope:stabox.MovieFile)
  })
_sym_db.RegisterMessage(MovieFile)



_MOVIES = _descriptor.ServiceDescriptor(
  name='Movies',
  full_name='stabox.Movies',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=123,
  serialized_end=186,
  methods=[
  _descriptor.MethodDescriptor(
    name='getFileInfo',
    full_name='stabox.Movies.getFileInfo',
    index=0,
    containing_service=None,
    input_type=_MOVIEFILE,
    output_type=_MOVIEFILE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOVIES)

DESCRIPTOR.services_by_name['Movies'] = _MOVIES

# @@protoc_insertion_point(module_scope)
