# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nimble.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nimble.proto',
  package='stabox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cnimble.proto\x12\x06stabox\"\xcb\x05\n\x0fNimbleReportReq\x12?\n\x0ePayPerViewInfo\x18\x04 \x01(\x0b\x32\'.stabox.NimbleReportReq.PayPerViewInfo_\x12\r\n\x05vhost\x18\x05 \x01(\t\x1a\xe7\x04\n\x0fPayPerViewInfo_\x12=\n\x05VHost\x18\x01 \x03(\x0b\x32..stabox.NimbleReportReq.PayPerViewInfo_.VHost_\x1a\x94\x04\n\x06VHost_\x12\x0c\n\x04name\x18\x01 \x01(\t\x12P\n\x0b\x41pplication\x18\x02 \x03(\x0b\x32;.stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_\x1a\xa9\x03\n\x0c\x41pplication_\x12\x0c\n\x04name\x18\x01 \x01(\t\x12W\n\x08Instance\x18\x02 \x03(\x0b\x32\x45.stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_\x1a\xb1\x02\n\tInstance_\x12\x0c\n\x04name\x18\x01 \x01(\t\x12]\n\x06Stream\x18\x02 \x03(\x0b\x32M.stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_\x1a\xb6\x01\n\x07Stream_\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x65\n\x06Player\x18\x02 \x03(\x0b\x32U.stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_.Player_\x1a\x36\n\x07Player_\x12\n\n\x02id\x18\x03 \x01(\t\x12\n\n\x02ip\x18\x04 \x01(\t\x12\x13\n\x0buser_agents\x18\x06 \x03(\t\"_\n\x0fNimbleReportRep\x12\x33\n\x08\x44\x65nyList\x18\x01 \x01(\x0b\x32!.stabox.NimbleReportRep.DenyList_\x1a\x17\n\tDenyList_\x12\n\n\x02ID\x18\x01 \x03(\tb\x06proto3')
)




_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE__STREAM__PLAYER_ = _descriptor.Descriptor(
  name='Player_',
  full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_.Player_',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_.Player_.id', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_.Player_.ip', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_agents', full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_.Player_.user_agents', index=2,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=740,
)

_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE__STREAM_ = _descriptor.Descriptor(
  name='Stream_',
  full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Player', full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_.Player', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE__STREAM__PLAYER_, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=558,
  serialized_end=740,
)

_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE_ = _descriptor.Descriptor(
  name='Instance_',
  full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Stream', full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE__STREAM_, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=740,
)

_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION_ = _descriptor.Descriptor(
  name='Application_',
  full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Instance', full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE_, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=740,
)

_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST_ = _descriptor.Descriptor(
  name='VHost_',
  full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Application', full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION_, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=740,
)

_NIMBLEREPORTREQ_PAYPERVIEWINFO_ = _descriptor.Descriptor(
  name='PayPerViewInfo_',
  full_name='stabox.NimbleReportReq.PayPerViewInfo_',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='VHost', full_name='stabox.NimbleReportReq.PayPerViewInfo_.VHost', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST_, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=740,
)

_NIMBLEREPORTREQ = _descriptor.Descriptor(
  name='NimbleReportReq',
  full_name='stabox.NimbleReportReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PayPerViewInfo', full_name='stabox.NimbleReportReq.PayPerViewInfo', index=0,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vhost', full_name='stabox.NimbleReportReq.vhost', index=1,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NIMBLEREPORTREQ_PAYPERVIEWINFO_, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=740,
)


_NIMBLEREPORTREP_DENYLIST_ = _descriptor.Descriptor(
  name='DenyList_',
  full_name='stabox.NimbleReportRep.DenyList_',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='stabox.NimbleReportRep.DenyList_.ID', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=814,
  serialized_end=837,
)

_NIMBLEREPORTREP = _descriptor.Descriptor(
  name='NimbleReportRep',
  full_name='stabox.NimbleReportRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='DenyList', full_name='stabox.NimbleReportRep.DenyList', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NIMBLEREPORTREP_DENYLIST_, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=742,
  serialized_end=837,
)

_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE__STREAM__PLAYER_.containing_type = _NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE__STREAM_
_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE__STREAM_.fields_by_name['Player'].message_type = _NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE__STREAM__PLAYER_
_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE__STREAM_.containing_type = _NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE_
_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE_.fields_by_name['Stream'].message_type = _NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE__STREAM_
_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE_.containing_type = _NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION_
_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION_.fields_by_name['Instance'].message_type = _NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE_
_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION_.containing_type = _NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST_
_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST_.fields_by_name['Application'].message_type = _NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION_
_NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST_.containing_type = _NIMBLEREPORTREQ_PAYPERVIEWINFO_
_NIMBLEREPORTREQ_PAYPERVIEWINFO_.fields_by_name['VHost'].message_type = _NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST_
_NIMBLEREPORTREQ_PAYPERVIEWINFO_.containing_type = _NIMBLEREPORTREQ
_NIMBLEREPORTREQ.fields_by_name['PayPerViewInfo'].message_type = _NIMBLEREPORTREQ_PAYPERVIEWINFO_
_NIMBLEREPORTREP_DENYLIST_.containing_type = _NIMBLEREPORTREP
_NIMBLEREPORTREP.fields_by_name['DenyList'].message_type = _NIMBLEREPORTREP_DENYLIST_
DESCRIPTOR.message_types_by_name['NimbleReportReq'] = _NIMBLEREPORTREQ
DESCRIPTOR.message_types_by_name['NimbleReportRep'] = _NIMBLEREPORTREP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NimbleReportReq = _reflection.GeneratedProtocolMessageType('NimbleReportReq', (_message.Message,), {

  'PayPerViewInfo_' : _reflection.GeneratedProtocolMessageType('PayPerViewInfo_', (_message.Message,), {

    'VHost_' : _reflection.GeneratedProtocolMessageType('VHost_', (_message.Message,), {

      'Application_' : _reflection.GeneratedProtocolMessageType('Application_', (_message.Message,), {

        'Instance_' : _reflection.GeneratedProtocolMessageType('Instance_', (_message.Message,), {

          'Stream_' : _reflection.GeneratedProtocolMessageType('Stream_', (_message.Message,), {

            'Player_' : _reflection.GeneratedProtocolMessageType('Player_', (_message.Message,), {
              'DESCRIPTOR' : _NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE__STREAM__PLAYER_,
              '__module__' : 'nimble_pb2'
              # @@protoc_insertion_point(class_scope:stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_.Player_)
              })
            ,
            'DESCRIPTOR' : _NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE__STREAM_,
            '__module__' : 'nimble_pb2'
            # @@protoc_insertion_point(class_scope:stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_)
            })
          ,
          'DESCRIPTOR' : _NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION__INSTANCE_,
          '__module__' : 'nimble_pb2'
          # @@protoc_insertion_point(class_scope:stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_)
          })
        ,
        'DESCRIPTOR' : _NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST__APPLICATION_,
        '__module__' : 'nimble_pb2'
        # @@protoc_insertion_point(class_scope:stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_)
        })
      ,
      'DESCRIPTOR' : _NIMBLEREPORTREQ_PAYPERVIEWINFO__VHOST_,
      '__module__' : 'nimble_pb2'
      # @@protoc_insertion_point(class_scope:stabox.NimbleReportReq.PayPerViewInfo_.VHost_)
      })
    ,
    'DESCRIPTOR' : _NIMBLEREPORTREQ_PAYPERVIEWINFO_,
    '__module__' : 'nimble_pb2'
    # @@protoc_insertion_point(class_scope:stabox.NimbleReportReq.PayPerViewInfo_)
    })
  ,
  'DESCRIPTOR' : _NIMBLEREPORTREQ,
  '__module__' : 'nimble_pb2'
  # @@protoc_insertion_point(class_scope:stabox.NimbleReportReq)
  })
_sym_db.RegisterMessage(NimbleReportReq)
_sym_db.RegisterMessage(NimbleReportReq.PayPerViewInfo_)
_sym_db.RegisterMessage(NimbleReportReq.PayPerViewInfo_.VHost_)
_sym_db.RegisterMessage(NimbleReportReq.PayPerViewInfo_.VHost_.Application_)
_sym_db.RegisterMessage(NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_)
_sym_db.RegisterMessage(NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_)
_sym_db.RegisterMessage(NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_.Player_)

NimbleReportRep = _reflection.GeneratedProtocolMessageType('NimbleReportRep', (_message.Message,), {

  'DenyList_' : _reflection.GeneratedProtocolMessageType('DenyList_', (_message.Message,), {
    'DESCRIPTOR' : _NIMBLEREPORTREP_DENYLIST_,
    '__module__' : 'nimble_pb2'
    # @@protoc_insertion_point(class_scope:stabox.NimbleReportRep.DenyList_)
    })
  ,
  'DESCRIPTOR' : _NIMBLEREPORTREP,
  '__module__' : 'nimble_pb2'
  # @@protoc_insertion_point(class_scope:stabox.NimbleReportRep)
  })
_sym_db.RegisterMessage(NimbleReportRep)
_sym_db.RegisterMessage(NimbleReportRep.DenyList_)


# @@protoc_insertion_point(module_scope)
