# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import services_pb2 as services__pb2


class ServicesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getColos = channel.unary_unary(
        '/stabox.Services/getColos',
        request_serializer=services__pb2.Nothing.SerializeToString,
        response_deserializer=services__pb2.GetColosRep.FromString,
        )
    self.GetColo = channel.unary_unary(
        '/stabox.Services/GetColo',
        request_serializer=services__pb2.Colo.SerializeToString,
        response_deserializer=services__pb2.Colo.FromString,
        )
    self.getServices = channel.unary_unary(
        '/stabox.Services/getServices',
        request_serializer=services__pb2.Nothing.SerializeToString,
        response_deserializer=services__pb2.GetServicesRep.FromString,
        )


class ServicesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getColos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetColo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getServices(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServicesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getColos': grpc.unary_unary_rpc_method_handler(
          servicer.getColos,
          request_deserializer=services__pb2.Nothing.FromString,
          response_serializer=services__pb2.GetColosRep.SerializeToString,
      ),
      'GetColo': grpc.unary_unary_rpc_method_handler(
          servicer.GetColo,
          request_deserializer=services__pb2.Colo.FromString,
          response_serializer=services__pb2.Colo.SerializeToString,
      ),
      'getServices': grpc.unary_unary_rpc_method_handler(
          servicer.getServices,
          request_deserializer=services__pb2.Nothing.FromString,
          response_serializer=services__pb2.GetServicesRep.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'stabox.Services', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
