# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='services.proto',
  package='stabox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eservices.proto\x12\x06stabox\x1a\x1cgoogle/api/annotations.proto\"}\n\x04\x43olo\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63olo_id\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x11\n\x07\x65nabled\x18\x05 \x01(\x08H\x00\x12\x10\n\x06public\x18\x06 \x01(\x08H\x01\x42\n\n\x08\x65nabled_B\t\n\x07public_\"\xa1\x01\n\x07Service\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\x12\n\nservice_id\x18\x02 \x01(\r\x12\x10\n\x08priority\x18\x03 \x01(\r\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x11\n\tcolo_name\x18\x05 \x01(\t\x12\x0f\n\x07handler\x18\x06 \x01(\t\x12\x0f\n\x07\x63omment\x18\x07 \x01(\t\x12\x11\n\x07\x65nabled\x18\x08 \x01(\x08H\x00\x42\n\n\x08\x65nabled_\"\t\n\x07Nothing\"9\n\x0bGetColosRep\x12\x1b\n\x05items\x18\x01 \x03(\x0b\x32\x0c.stabox.Colo\x12\r\n\x05total\x18\x02 \x01(\r\"?\n\x0eGetServicesRep\x12\x1e\n\x05items\x18\x01 \x03(\x0b\x32\x0f.stabox.Service\x12\r\n\x05total\x18\x02 \x01(\r2\xc0\x01\n\x08Services\x12@\n\x08getColos\x12\x0f.stabox.Nothing\x1a\x13.stabox.GetColosRep\"\x0e\x82\xd3\xe4\x93\x02\x08\x12\x06/colos\x12\'\n\x07GetColo\x12\x0c.stabox.Colo\x1a\x0c.stabox.Colo\"\x00\x12I\n\x0bgetServices\x12\x0f.stabox.Nothing\x1a\x16.stabox.GetServicesRep\"\x11\x82\xd3\xe4\x93\x02\x0b\x12\t/servicesb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_COLO = _descriptor.Descriptor(
  name='Colo',
  full_name='stabox.Colo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_id', full_name='stabox.Colo._id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colo_id', full_name='stabox.Colo.colo_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='stabox.Colo.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='stabox.Colo.title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='stabox.Colo.enabled', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='public', full_name='stabox.Colo.public', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='enabled_', full_name='stabox.Colo.enabled_',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='public_', full_name='stabox.Colo.public_',
      index=1, containing_type=None, fields=[]),
  ],
  serialized_start=56,
  serialized_end=181,
)


_SERVICE = _descriptor.Descriptor(
  name='Service',
  full_name='stabox.Service',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='_id', full_name='stabox.Service._id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_id', full_name='stabox.Service.service_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='stabox.Service.priority', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='stabox.Service.address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colo_name', full_name='stabox.Service.colo_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='handler', full_name='stabox.Service.handler', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='stabox.Service.comment', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='stabox.Service.enabled', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='enabled_', full_name='stabox.Service.enabled_',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=184,
  serialized_end=345,
)


_NOTHING = _descriptor.Descriptor(
  name='Nothing',
  full_name='stabox.Nothing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=356,
)


_GETCOLOSREP = _descriptor.Descriptor(
  name='GetColosRep',
  full_name='stabox.GetColosRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='stabox.GetColosRep.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='stabox.GetColosRep.total', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=415,
)


_GETSERVICESREP = _descriptor.Descriptor(
  name='GetServicesRep',
  full_name='stabox.GetServicesRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='stabox.GetServicesRep.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='stabox.GetServicesRep.total', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=480,
)

_COLO.oneofs_by_name['enabled_'].fields.append(
  _COLO.fields_by_name['enabled'])
_COLO.fields_by_name['enabled'].containing_oneof = _COLO.oneofs_by_name['enabled_']
_COLO.oneofs_by_name['public_'].fields.append(
  _COLO.fields_by_name['public'])
_COLO.fields_by_name['public'].containing_oneof = _COLO.oneofs_by_name['public_']
_SERVICE.oneofs_by_name['enabled_'].fields.append(
  _SERVICE.fields_by_name['enabled'])
_SERVICE.fields_by_name['enabled'].containing_oneof = _SERVICE.oneofs_by_name['enabled_']
_GETCOLOSREP.fields_by_name['items'].message_type = _COLO
_GETSERVICESREP.fields_by_name['items'].message_type = _SERVICE
DESCRIPTOR.message_types_by_name['Colo'] = _COLO
DESCRIPTOR.message_types_by_name['Service'] = _SERVICE
DESCRIPTOR.message_types_by_name['Nothing'] = _NOTHING
DESCRIPTOR.message_types_by_name['GetColosRep'] = _GETCOLOSREP
DESCRIPTOR.message_types_by_name['GetServicesRep'] = _GETSERVICESREP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Colo = _reflection.GeneratedProtocolMessageType('Colo', (_message.Message,), {
  'DESCRIPTOR' : _COLO,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:stabox.Colo)
  })
_sym_db.RegisterMessage(Colo)

Service = _reflection.GeneratedProtocolMessageType('Service', (_message.Message,), {
  'DESCRIPTOR' : _SERVICE,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:stabox.Service)
  })
_sym_db.RegisterMessage(Service)

Nothing = _reflection.GeneratedProtocolMessageType('Nothing', (_message.Message,), {
  'DESCRIPTOR' : _NOTHING,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:stabox.Nothing)
  })
_sym_db.RegisterMessage(Nothing)

GetColosRep = _reflection.GeneratedProtocolMessageType('GetColosRep', (_message.Message,), {
  'DESCRIPTOR' : _GETCOLOSREP,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:stabox.GetColosRep)
  })
_sym_db.RegisterMessage(GetColosRep)

GetServicesRep = _reflection.GeneratedProtocolMessageType('GetServicesRep', (_message.Message,), {
  'DESCRIPTOR' : _GETSERVICESREP,
  '__module__' : 'services_pb2'
  # @@protoc_insertion_point(class_scope:stabox.GetServicesRep)
  })
_sym_db.RegisterMessage(GetServicesRep)



_SERVICES = _descriptor.ServiceDescriptor(
  name='Services',
  full_name='stabox.Services',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=483,
  serialized_end=675,
  methods=[
  _descriptor.MethodDescriptor(
    name='getColos',
    full_name='stabox.Services.getColos',
    index=0,
    containing_service=None,
    input_type=_NOTHING,
    output_type=_GETCOLOSREP,
    serialized_options=_b('\202\323\344\223\002\010\022\006/colos'),
  ),
  _descriptor.MethodDescriptor(
    name='GetColo',
    full_name='stabox.Services.GetColo',
    index=1,
    containing_service=None,
    input_type=_COLO,
    output_type=_COLO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getServices',
    full_name='stabox.Services.getServices',
    index=2,
    containing_service=None,
    input_type=_NOTHING,
    output_type=_GETSERVICESREP,
    serialized_options=_b('\202\323\344\223\002\013\022\t/services'),
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICES)

DESCRIPTOR.services_by_name['Services'] = _SERVICES

# @@protoc_insertion_point(module_scope)
