// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nimble.proto

package stabox

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Commented out fields currently not handled
type NimbleReportReq struct {
	// string ID = 1;
	// string Puzzle = 2;
	// string Signature = 3;
	PayPerViewInfo       *NimbleReportReq_PayPerViewInfo_ `protobuf:"bytes,4,opt,name=PayPerViewInfo,proto3" json:"PayPerViewInfo,omitempty"`
	Vhost                string                           `protobuf:"bytes,5,opt,name=vhost,proto3" json:"vhost,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *NimbleReportReq) Reset()         { *m = NimbleReportReq{} }
func (m *NimbleReportReq) String() string { return proto.CompactTextString(m) }
func (*NimbleReportReq) ProtoMessage()    {}
func (*NimbleReportReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_54eb39ddc3aeb4df, []int{0}
}

func (m *NimbleReportReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NimbleReportReq.Unmarshal(m, b)
}
func (m *NimbleReportReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NimbleReportReq.Marshal(b, m, deterministic)
}
func (m *NimbleReportReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NimbleReportReq.Merge(m, src)
}
func (m *NimbleReportReq) XXX_Size() int {
	return xxx_messageInfo_NimbleReportReq.Size(m)
}
func (m *NimbleReportReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NimbleReportReq.DiscardUnknown(m)
}

var xxx_messageInfo_NimbleReportReq proto.InternalMessageInfo

func (m *NimbleReportReq) GetPayPerViewInfo() *NimbleReportReq_PayPerViewInfo_ {
	if m != nil {
		return m.PayPerViewInfo
	}
	return nil
}

func (m *NimbleReportReq) GetVhost() string {
	if m != nil {
		return m.Vhost
	}
	return ""
}

type NimbleReportReq_PayPerViewInfo_ struct {
	VHost                []*NimbleReportReq_PayPerViewInfo__VHost_ `protobuf:"bytes,1,rep,name=VHost,proto3" json:"VHost,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *NimbleReportReq_PayPerViewInfo_) Reset()         { *m = NimbleReportReq_PayPerViewInfo_{} }
func (m *NimbleReportReq_PayPerViewInfo_) String() string { return proto.CompactTextString(m) }
func (*NimbleReportReq_PayPerViewInfo_) ProtoMessage()    {}
func (*NimbleReportReq_PayPerViewInfo_) Descriptor() ([]byte, []int) {
	return fileDescriptor_54eb39ddc3aeb4df, []int{0, 0}
}

func (m *NimbleReportReq_PayPerViewInfo_) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo_.Unmarshal(m, b)
}
func (m *NimbleReportReq_PayPerViewInfo_) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo_.Marshal(b, m, deterministic)
}
func (m *NimbleReportReq_PayPerViewInfo_) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NimbleReportReq_PayPerViewInfo_.Merge(m, src)
}
func (m *NimbleReportReq_PayPerViewInfo_) XXX_Size() int {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo_.Size(m)
}
func (m *NimbleReportReq_PayPerViewInfo_) XXX_DiscardUnknown() {
	xxx_messageInfo_NimbleReportReq_PayPerViewInfo_.DiscardUnknown(m)
}

var xxx_messageInfo_NimbleReportReq_PayPerViewInfo_ proto.InternalMessageInfo

func (m *NimbleReportReq_PayPerViewInfo_) GetVHost() []*NimbleReportReq_PayPerViewInfo__VHost_ {
	if m != nil {
		return m.VHost
	}
	return nil
}

type NimbleReportReq_PayPerViewInfo__VHost_ struct {
	Name                 string                                                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Application          []*NimbleReportReq_PayPerViewInfo__VHost__Application_ `protobuf:"bytes,2,rep,name=Application,proto3" json:"Application,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                               `json:"-"`
	XXX_unrecognized     []byte                                                 `json:"-"`
	XXX_sizecache        int32                                                  `json:"-"`
}

func (m *NimbleReportReq_PayPerViewInfo__VHost_) Reset() {
	*m = NimbleReportReq_PayPerViewInfo__VHost_{}
}
func (m *NimbleReportReq_PayPerViewInfo__VHost_) String() string { return proto.CompactTextString(m) }
func (*NimbleReportReq_PayPerViewInfo__VHost_) ProtoMessage()    {}
func (*NimbleReportReq_PayPerViewInfo__VHost_) Descriptor() ([]byte, []int) {
	return fileDescriptor_54eb39ddc3aeb4df, []int{0, 0, 0}
}

func (m *NimbleReportReq_PayPerViewInfo__VHost_) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost_.Unmarshal(m, b)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost_) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost_.Marshal(b, m, deterministic)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost_) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost_.Merge(m, src)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost_) XXX_Size() int {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost_.Size(m)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost_) XXX_DiscardUnknown() {
	xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost_.DiscardUnknown(m)
}

var xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost_ proto.InternalMessageInfo

func (m *NimbleReportReq_PayPerViewInfo__VHost_) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NimbleReportReq_PayPerViewInfo__VHost_) GetApplication() []*NimbleReportReq_PayPerViewInfo__VHost__Application_ {
	if m != nil {
		return m.Application
	}
	return nil
}

type NimbleReportReq_PayPerViewInfo__VHost__Application_ struct {
	Name                 string                                                           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Instance             []*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_ `protobuf:"bytes,2,rep,name=Instance,proto3" json:"Instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                         `json:"-"`
	XXX_unrecognized     []byte                                                           `json:"-"`
	XXX_sizecache        int32                                                            `json:"-"`
}

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application_) Reset() {
	*m = NimbleReportReq_PayPerViewInfo__VHost__Application_{}
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application_) String() string {
	return proto.CompactTextString(m)
}
func (*NimbleReportReq_PayPerViewInfo__VHost__Application_) ProtoMessage() {}
func (*NimbleReportReq_PayPerViewInfo__VHost__Application_) Descriptor() ([]byte, []int) {
	return fileDescriptor_54eb39ddc3aeb4df, []int{0, 0, 0, 0}
}

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application_) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application_.Unmarshal(m, b)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application_) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application_.Marshal(b, m, deterministic)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application_) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application_.Merge(m, src)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application_) XXX_Size() int {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application_.Size(m)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application_) XXX_DiscardUnknown() {
	xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application_.DiscardUnknown(m)
}

var xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application_ proto.InternalMessageInfo

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application_) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application_) GetInstance() []*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_ {
	if m != nil {
		return m.Instance
	}
	return nil
}

type NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_ struct {
	Name                 string                                                                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stream               []*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_ `protobuf:"bytes,2,rep,name=Stream,proto3" json:"Stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                 `json:"-"`
	XXX_unrecognized     []byte                                                                   `json:"-"`
	XXX_sizecache        int32                                                                    `json:"-"`
}

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_) Reset() {
	*m = NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_{}
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_) String() string {
	return proto.CompactTextString(m)
}
func (*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_) ProtoMessage() {}
func (*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_) Descriptor() ([]byte, []int) {
	return fileDescriptor_54eb39ddc3aeb4df, []int{0, 0, 0, 0, 0}
}

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_.Unmarshal(m, b)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_.Marshal(b, m, deterministic)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_.Merge(m, src)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_) XXX_Size() int {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_.Size(m)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_) XXX_DiscardUnknown() {
	xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_.DiscardUnknown(m)
}

var xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_ proto.InternalMessageInfo

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_) GetStream() []*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_ {
	if m != nil {
		return m.Stream
	}
	return nil
}

type NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_ struct {
	Name                 string                                                                           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Player               []*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_ `protobuf:"bytes,2,rep,name=Player,proto3" json:"Player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                         `json:"-"`
	XXX_unrecognized     []byte                                                                           `json:"-"`
	XXX_sizecache        int32                                                                            `json:"-"`
}

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_) Reset() {
	*m = NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_{}
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_) String() string {
	return proto.CompactTextString(m)
}
func (*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_) ProtoMessage() {}
func (*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_) Descriptor() ([]byte, []int) {
	return fileDescriptor_54eb39ddc3aeb4df, []int{0, 0, 0, 0, 0, 0}
}

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_.Unmarshal(m, b)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_.Marshal(b, m, deterministic)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_.Merge(m, src)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_) XXX_Size() int {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_.Size(m)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_) XXX_DiscardUnknown() {
	xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_.DiscardUnknown(m)
}

var xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_ proto.InternalMessageInfo

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_) GetPlayer() []*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_ {
	if m != nil {
		return m.Player
	}
	return nil
}

type NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_ struct {
	// uint32 bytes_sent = 1;
	// uint32 delta = 2;
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Ip string `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	// string sessionid = 5;
	UserAgents           []string `protobuf:"bytes,6,rep,name=user_agents,json=userAgents,proto3" json:"user_agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_) Reset() {
	*m = NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_{}
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_) String() string {
	return proto.CompactTextString(m)
}
func (*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_) ProtoMessage() {}
func (*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_) Descriptor() ([]byte, []int) {
	return fileDescriptor_54eb39ddc3aeb4df, []int{0, 0, 0, 0, 0, 0, 0}
}

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_.Unmarshal(m, b)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_.Marshal(b, m, deterministic)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_.Merge(m, src)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_) XXX_Size() int {
	return xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_.Size(m)
}
func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_) XXX_DiscardUnknown() {
	xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_.DiscardUnknown(m)
}

var xxx_messageInfo_NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_ proto.InternalMessageInfo

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_) GetUserAgents() []string {
	if m != nil {
		return m.UserAgents
	}
	return nil
}

type NimbleReportRep struct {
	DenyList             *NimbleReportRep_DenyList_ `protobuf:"bytes,1,opt,name=DenyList,proto3" json:"DenyList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *NimbleReportRep) Reset()         { *m = NimbleReportRep{} }
func (m *NimbleReportRep) String() string { return proto.CompactTextString(m) }
func (*NimbleReportRep) ProtoMessage()    {}
func (*NimbleReportRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_54eb39ddc3aeb4df, []int{1}
}

func (m *NimbleReportRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NimbleReportRep.Unmarshal(m, b)
}
func (m *NimbleReportRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NimbleReportRep.Marshal(b, m, deterministic)
}
func (m *NimbleReportRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NimbleReportRep.Merge(m, src)
}
func (m *NimbleReportRep) XXX_Size() int {
	return xxx_messageInfo_NimbleReportRep.Size(m)
}
func (m *NimbleReportRep) XXX_DiscardUnknown() {
	xxx_messageInfo_NimbleReportRep.DiscardUnknown(m)
}

var xxx_messageInfo_NimbleReportRep proto.InternalMessageInfo

func (m *NimbleReportRep) GetDenyList() *NimbleReportRep_DenyList_ {
	if m != nil {
		return m.DenyList
	}
	return nil
}

type NimbleReportRep_DenyList_ struct {
	ID                   []string `protobuf:"bytes,1,rep,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NimbleReportRep_DenyList_) Reset()         { *m = NimbleReportRep_DenyList_{} }
func (m *NimbleReportRep_DenyList_) String() string { return proto.CompactTextString(m) }
func (*NimbleReportRep_DenyList_) ProtoMessage()    {}
func (*NimbleReportRep_DenyList_) Descriptor() ([]byte, []int) {
	return fileDescriptor_54eb39ddc3aeb4df, []int{1, 0}
}

func (m *NimbleReportRep_DenyList_) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NimbleReportRep_DenyList_.Unmarshal(m, b)
}
func (m *NimbleReportRep_DenyList_) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NimbleReportRep_DenyList_.Marshal(b, m, deterministic)
}
func (m *NimbleReportRep_DenyList_) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NimbleReportRep_DenyList_.Merge(m, src)
}
func (m *NimbleReportRep_DenyList_) XXX_Size() int {
	return xxx_messageInfo_NimbleReportRep_DenyList_.Size(m)
}
func (m *NimbleReportRep_DenyList_) XXX_DiscardUnknown() {
	xxx_messageInfo_NimbleReportRep_DenyList_.DiscardUnknown(m)
}

var xxx_messageInfo_NimbleReportRep_DenyList_ proto.InternalMessageInfo

func (m *NimbleReportRep_DenyList_) GetID() []string {
	if m != nil {
		return m.ID
	}
	return nil
}

func init() {
	proto.RegisterType((*NimbleReportReq)(nil), "stabox.NimbleReportReq")
	proto.RegisterType((*NimbleReportReq_PayPerViewInfo_)(nil), "stabox.NimbleReportReq.PayPerViewInfo_")
	proto.RegisterType((*NimbleReportReq_PayPerViewInfo__VHost_)(nil), "stabox.NimbleReportReq.PayPerViewInfo_.VHost_")
	proto.RegisterType((*NimbleReportReq_PayPerViewInfo__VHost__Application_)(nil), "stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_")
	proto.RegisterType((*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance_)(nil), "stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_")
	proto.RegisterType((*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream_)(nil), "stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_")
	proto.RegisterType((*NimbleReportReq_PayPerViewInfo__VHost__Application__Instance__Stream__Player_)(nil), "stabox.NimbleReportReq.PayPerViewInfo_.VHost_.Application_.Instance_.Stream_.Player_")
	proto.RegisterType((*NimbleReportRep)(nil), "stabox.NimbleReportRep")
	proto.RegisterType((*NimbleReportRep_DenyList_)(nil), "stabox.NimbleReportRep.DenyList_")
}

func init() { proto.RegisterFile("nimble.proto", fileDescriptor_54eb39ddc3aeb4df) }

var fileDescriptor_54eb39ddc3aeb4df = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x3f, 0x8f, 0x9b, 0x30,
	0x18, 0xc6, 0x05, 0x04, 0x12, 0x5e, 0xa2, 0x44, 0xb2, 0x3a, 0x20, 0x3a, 0x94, 0x66, 0x29, 0x93,
	0x87, 0x74, 0xac, 0x3a, 0x44, 0xa2, 0x52, 0xa9, 0xfa, 0x27, 0x72, 0xd5, 0x6c, 0x95, 0xe5, 0x24,
	0x6e, 0x8b, 0x14, 0x8c, 0x0b, 0xbe, 0x3f, 0xf9, 0x6e, 0xb7, 0xdc, 0xb7, 0xb8, 0xf5, 0xa6, 0xd3,
	0x7d, 0x8b, 0x13, 0x86, 0xa0, 0x1c, 0x62, 0xb8, 0xd3, 0x65, 0xc3, 0x8f, 0xdf, 0xe7, 0x79, 0x7e,
	0x48, 0x7e, 0x61, 0x2c, 0xd2, 0x6c, 0xbd, 0xe3, 0x58, 0x16, 0xb9, 0xca, 0x91, 0x53, 0x2a, 0xb6,
	0xce, 0x2f, 0x67, 0x57, 0x0e, 0x4c, 0xbf, 0xeb, 0x0b, 0xc2, 0x65, 0x5e, 0x28, 0xc2, 0xff, 0xa3,
	0x1f, 0x30, 0x59, 0xb2, 0xfd, 0x92, 0x17, 0xab, 0x94, 0x5f, 0x24, 0xe2, 0x4f, 0xee, 0x0f, 0x42,
	0x23, 0xf2, 0xe6, 0xef, 0x70, 0x6d, 0xc2, 0x1d, 0x03, 0x7e, 0x3c, 0x4d, 0x49, 0xc7, 0x8e, 0x5e,
	0x81, 0x7d, 0xfe, 0x2f, 0x2f, 0x95, 0x6f, 0x87, 0x46, 0xe4, 0x92, 0xfa, 0x10, 0x5c, 0xdb, 0x30,
	0xed, 0x38, 0x51, 0x0c, 0xf6, 0xea, 0x73, 0x35, 0x69, 0x84, 0x56, 0xe4, 0xcd, 0xf1, 0x13, 0x1b,
	0xb1, 0x36, 0x51, 0x52, 0x9b, 0x83, 0xbb, 0x01, 0x38, 0xb5, 0x82, 0x10, 0x0c, 0x04, 0xcb, 0xb8,
	0x6f, 0xe8, 0x66, 0xfd, 0x8d, 0x7e, 0x83, 0xb7, 0x90, 0x72, 0x97, 0x6e, 0x98, 0x4a, 0x73, 0xe1,
	0x9b, 0xba, 0xea, 0xc3, 0xf3, 0xaa, 0xf0, 0x51, 0x02, 0x25, 0xc7, 0x79, 0xc1, 0xbd, 0x05, 0xe3,
	0xe3, 0xdb, 0x5e, 0x06, 0x06, 0xa3, 0x44, 0x94, 0x8a, 0x89, 0x0d, 0x6f, 0x00, 0x3e, 0xbd, 0x00,
	0x00, 0x1f, 0xb2, 0x28, 0x69, 0x63, 0x83, 0x5b, 0x13, 0xdc, 0x56, 0xef, 0x85, 0xe0, 0xe0, 0xfc,
	0x54, 0x05, 0x67, 0x59, 0x83, 0xf0, 0xed, 0x24, 0x08, 0xb8, 0xce, 0xa4, 0xa4, 0x09, 0x0f, 0x6e,
	0x0c, 0x18, 0x36, 0x5a, 0x2f, 0x46, 0x06, 0xce, 0x72, 0xc7, 0xf6, 0xbc, 0x68, 0x30, 0x7e, 0x9d,
	0x14, 0x03, 0xd7, 0xd9, 0x94, 0x34, 0x25, 0xc1, 0x17, 0x18, 0x36, 0x12, 0x9a, 0x80, 0x99, 0x6e,
	0x7d, 0x4b, 0xb3, 0x98, 0xe9, 0x56, 0x9f, 0xa5, 0x7e, 0xed, 0xd5, 0x59, 0xa2, 0x37, 0xe0, 0x9d,
	0x95, 0xbc, 0xa0, 0xec, 0x2f, 0x17, 0xaa, 0xf4, 0x9d, 0xd0, 0x8a, 0x5c, 0x02, 0x95, 0xb4, 0xd0,
	0xca, 0x2c, 0xeb, 0x6e, 0x8f, 0x44, 0x1f, 0x61, 0x14, 0x73, 0xb1, 0xff, 0x9a, 0xea, 0x57, 0x5c,
	0xed, 0xcd, 0xdb, 0xfe, 0xff, 0x91, 0xf8, 0x30, 0x47, 0x49, 0x6b, 0x09, 0x5e, 0x83, 0xdb, 0xca,
	0x15, 0x4f, 0x12, 0xeb, 0x5d, 0x70, 0x89, 0x99, 0xc4, 0x6b, 0x47, 0x2f, 0xef, 0xfb, 0x87, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe9, 0xb4, 0x0f, 0xe7, 0xcc, 0x03, 0x00, 0x00,
}
