// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services.proto

package stabox

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Colo struct {
	XId    string `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	ColoId uint32 `protobuf:"varint,2,opt,name=colo_id,json=coloId,proto3" json:"colo_id,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Title  string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// Types that are valid to be assigned to Enabled_:
	//	*Colo_Enabled
	Enabled_ isColo_Enabled_ `protobuf_oneof:"enabled_"`
	// Types that are valid to be assigned to Public_:
	//	*Colo_Public
	Public_              isColo_Public_ `protobuf_oneof:"public_"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Colo) Reset()         { *m = Colo{} }
func (m *Colo) String() string { return proto.CompactTextString(m) }
func (*Colo) ProtoMessage()    {}
func (*Colo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{0}
}

func (m *Colo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Colo.Unmarshal(m, b)
}
func (m *Colo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Colo.Marshal(b, m, deterministic)
}
func (m *Colo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Colo.Merge(m, src)
}
func (m *Colo) XXX_Size() int {
	return xxx_messageInfo_Colo.Size(m)
}
func (m *Colo) XXX_DiscardUnknown() {
	xxx_messageInfo_Colo.DiscardUnknown(m)
}

var xxx_messageInfo_Colo proto.InternalMessageInfo

func (m *Colo) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *Colo) GetColoId() uint32 {
	if m != nil {
		return m.ColoId
	}
	return 0
}

func (m *Colo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Colo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type isColo_Enabled_ interface {
	isColo_Enabled_()
}

type Colo_Enabled struct {
	Enabled bool `protobuf:"varint,5,opt,name=enabled,proto3,oneof"`
}

func (*Colo_Enabled) isColo_Enabled_() {}

func (m *Colo) GetEnabled_() isColo_Enabled_ {
	if m != nil {
		return m.Enabled_
	}
	return nil
}

func (m *Colo) GetEnabled() bool {
	if x, ok := m.GetEnabled_().(*Colo_Enabled); ok {
		return x.Enabled
	}
	return false
}

type isColo_Public_ interface {
	isColo_Public_()
}

type Colo_Public struct {
	Public bool `protobuf:"varint,6,opt,name=public,proto3,oneof"`
}

func (*Colo_Public) isColo_Public_() {}

func (m *Colo) GetPublic_() isColo_Public_ {
	if m != nil {
		return m.Public_
	}
	return nil
}

func (m *Colo) GetPublic() bool {
	if x, ok := m.GetPublic_().(*Colo_Public); ok {
		return x.Public
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Colo) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Colo_Enabled)(nil),
		(*Colo_Public)(nil),
	}
}

type Service struct {
	XId       string `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	ServiceId uint32 `protobuf:"varint,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Priority  uint32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Address   string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	ColoName  string `protobuf:"bytes,5,opt,name=colo_name,json=coloName,proto3" json:"colo_name,omitempty"`
	Handler   string `protobuf:"bytes,6,opt,name=handler,proto3" json:"handler,omitempty"`
	Comment   string `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	// Types that are valid to be assigned to Enabled_:
	//	*Service_Enabled
	Enabled_             isService_Enabled_ `protobuf_oneof:"enabled_"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{1}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *Service) GetServiceId() uint32 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *Service) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Service) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Service) GetColoName() string {
	if m != nil {
		return m.ColoName
	}
	return ""
}

func (m *Service) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

func (m *Service) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type isService_Enabled_ interface {
	isService_Enabled_()
}

type Service_Enabled struct {
	Enabled bool `protobuf:"varint,8,opt,name=enabled,proto3,oneof"`
}

func (*Service_Enabled) isService_Enabled_() {}

func (m *Service) GetEnabled_() isService_Enabled_ {
	if m != nil {
		return m.Enabled_
	}
	return nil
}

func (m *Service) GetEnabled() bool {
	if x, ok := m.GetEnabled_().(*Service_Enabled); ok {
		return x.Enabled
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Service) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Service_Enabled)(nil),
	}
}

type Nothing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{2}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

type GetColosRep struct {
	Items                []*Colo  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total                uint32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetColosRep) Reset()         { *m = GetColosRep{} }
func (m *GetColosRep) String() string { return proto.CompactTextString(m) }
func (*GetColosRep) ProtoMessage()    {}
func (*GetColosRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{3}
}

func (m *GetColosRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetColosRep.Unmarshal(m, b)
}
func (m *GetColosRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetColosRep.Marshal(b, m, deterministic)
}
func (m *GetColosRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetColosRep.Merge(m, src)
}
func (m *GetColosRep) XXX_Size() int {
	return xxx_messageInfo_GetColosRep.Size(m)
}
func (m *GetColosRep) XXX_DiscardUnknown() {
	xxx_messageInfo_GetColosRep.DiscardUnknown(m)
}

var xxx_messageInfo_GetColosRep proto.InternalMessageInfo

func (m *GetColosRep) GetItems() []*Colo {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *GetColosRep) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type GetServicesRep struct {
	Items                []*Service `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total                uint32     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetServicesRep) Reset()         { *m = GetServicesRep{} }
func (m *GetServicesRep) String() string { return proto.CompactTextString(m) }
func (*GetServicesRep) ProtoMessage()    {}
func (*GetServicesRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{4}
}

func (m *GetServicesRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServicesRep.Unmarshal(m, b)
}
func (m *GetServicesRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServicesRep.Marshal(b, m, deterministic)
}
func (m *GetServicesRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServicesRep.Merge(m, src)
}
func (m *GetServicesRep) XXX_Size() int {
	return xxx_messageInfo_GetServicesRep.Size(m)
}
func (m *GetServicesRep) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServicesRep.DiscardUnknown(m)
}

var xxx_messageInfo_GetServicesRep proto.InternalMessageInfo

func (m *GetServicesRep) GetItems() []*Service {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *GetServicesRep) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*Colo)(nil), "stabox.Colo")
	proto.RegisterType((*Service)(nil), "stabox.Service")
	proto.RegisterType((*Nothing)(nil), "stabox.Nothing")
	proto.RegisterType((*GetColosRep)(nil), "stabox.GetColosRep")
	proto.RegisterType((*GetServicesRep)(nil), "stabox.GetServicesRep")
}

func init() { proto.RegisterFile("services.proto", fileDescriptor_8e16ccb8c5307b32) }

var fileDescriptor_8e16ccb8c5307b32 = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4b, 0x8e, 0xd4, 0x30,
	0x10, 0x1d, 0xf7, 0x27, 0x4e, 0xaa, 0x99, 0x1e, 0x51, 0x20, 0xb0, 0x02, 0x48, 0x2d, 0x4b, 0x88,
	0x5e, 0x75, 0x4b, 0xc3, 0x05, 0xd0, 0xb0, 0x68, 0x7a, 0xc1, 0x2c, 0xc2, 0x01, 0x5a, 0xee, 0xc4,
	0xca, 0x58, 0x72, 0xec, 0x28, 0x31, 0x08, 0xb6, 0x5c, 0x81, 0x43, 0x70, 0x0d, 0xee, 0xc0, 0x15,
	0x58, 0x70, 0x0c, 0x14, 0xc7, 0x99, 0x49, 0x33, 0xd2, 0xec, 0xf2, 0xde, 0xab, 0xbc, 0xaa, 0x57,
	0x25, 0xc3, 0xb2, 0x95, 0xcd, 0x17, 0x95, 0xcb, 0x76, 0x53, 0x37, 0xd6, 0x59, 0x8c, 0x5a, 0x27,
	0x8e, 0xf6, 0x6b, 0xfa, 0xb2, 0xb4, 0xb6, 0xd4, 0x72, 0x2b, 0x6a, 0xb5, 0x15, 0xc6, 0x58, 0x27,
	0x9c, 0xb2, 0x26, 0x54, 0xf1, 0x9f, 0x04, 0x66, 0xef, 0xad, 0xb6, 0x78, 0x01, 0xd3, 0x83, 0x2a,
	0x18, 0x59, 0x91, 0x75, 0x92, 0x4d, 0xf6, 0x05, 0x3e, 0x07, 0x9a, 0x5b, 0x6d, 0x3b, 0x72, 0xb2,
	0x22, 0xeb, 0xf3, 0x2c, 0xea, 0xe0, 0xbe, 0x40, 0x84, 0x99, 0x11, 0x95, 0x64, 0x53, 0x5f, 0xea,
	0xbf, 0xf1, 0x29, 0xcc, 0x9d, 0x72, 0x5a, 0xb2, 0x99, 0x27, 0x7b, 0x80, 0x29, 0x50, 0x69, 0xc4,
	0x51, 0xcb, 0x82, 0xcd, 0x57, 0x64, 0x1d, 0x7f, 0x38, 0xcb, 0x06, 0x02, 0x19, 0x44, 0xf5, 0xe7,
	0xa3, 0x56, 0x39, 0x8b, 0xbc, 0x44, 0xb2, 0x80, 0xaf, 0x00, 0xe2, 0x50, 0x74, 0xb8, 0x4a, 0x80,
	0xf6, 0xec, 0x81, 0xff, 0x25, 0x40, 0x3f, 0xf5, 0x11, 0xef, 0x0f, 0xfb, 0x0a, 0x20, 0xc4, 0xbf,
	0x9b, 0x37, 0x09, 0xcc, 0xbe, 0xc0, 0x14, 0xe2, 0xba, 0x51, 0xb6, 0x51, 0xee, 0x9b, 0x1f, 0xfb,
	0x3c, 0xbb, 0xc5, 0xc8, 0x80, 0x8a, 0xa2, 0x68, 0x64, 0xdb, 0x86, 0xe1, 0x07, 0x88, 0x2f, 0x20,
	0xf1, 0x1b, 0xf0, 0x69, 0xe7, 0x5e, 0x8b, 0x3b, 0xe2, 0xba, 0x4b, 0xcc, 0x80, 0xde, 0x08, 0x53,
	0x68, 0xd9, 0xf8, 0x00, 0x49, 0x36, 0xc0, 0x4e, 0xc9, 0x6d, 0x55, 0x49, 0xe3, 0x18, 0xed, 0x95,
	0x00, 0xc7, 0xfb, 0x88, 0xff, 0xdb, 0xc7, 0x38, 0x35, 0x4f, 0x80, 0x5e, 0x5b, 0x77, 0xa3, 0x4c,
	0xc9, 0x77, 0xb0, 0xd8, 0x49, 0xd7, 0x5d, 0xa8, 0xcd, 0x64, 0x8d, 0x1c, 0xe6, 0xca, 0xc9, 0xaa,
	0x65, 0x64, 0x35, 0x5d, 0x2f, 0x2e, 0x1f, 0x6d, 0xfa, 0x23, 0x6f, 0xba, 0x82, 0xac, 0x97, 0xfc,
	0x2d, 0xac, 0x13, 0x3a, 0xac, 0xa1, 0x07, 0xfc, 0x23, 0x2c, 0x77, 0xd2, 0x85, 0x05, 0x7a, 0xaf,
	0xd7, 0xa7, 0x5e, 0x17, 0x83, 0x57, 0xa8, 0x79, 0xd0, 0xee, 0xf2, 0x17, 0x81, 0x78, 0x30, 0xc3,
	0x77, 0x10, 0x97, 0x61, 0x48, 0xbc, 0xb5, 0x09, 0x09, 0xd2, 0x27, 0x03, 0x31, 0xca, 0xc1, 0x97,
	0xdf, 0x7f, 0xff, 0xf9, 0x31, 0x89, 0x31, 0xda, 0xe6, 0xfe, 0xaf, 0x37, 0x40, 0x83, 0x8c, 0x27,
	0x99, 0xd2, 0x13, 0xc4, 0xcf, 0x70, 0x0f, 0x8b, 0xf2, 0x2e, 0xc6, 0xfd, 0x6e, 0xcf, 0x46, 0xdd,
	0x46, 0x61, 0xf9, 0x63, 0xdf, 0x70, 0x81, 0xc9, 0x76, 0x78, 0x26, 0xc7, 0xc8, 0xbf, 0x80, 0xb7,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x79, 0xa8, 0xbd, 0x06, 0x39, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServicesClient is the client API for Services service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServicesClient interface {
	GetColos(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*GetColosRep, error)
	GetColo(ctx context.Context, in *Colo, opts ...grpc.CallOption) (*Colo, error)
	GetServices(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*GetServicesRep, error)
}

type servicesClient struct {
	cc *grpc.ClientConn
}

func NewServicesClient(cc *grpc.ClientConn) ServicesClient {
	return &servicesClient{cc}
}

func (c *servicesClient) GetColos(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*GetColosRep, error) {
	out := new(GetColosRep)
	err := c.cc.Invoke(ctx, "/stabox.Services/getColos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesClient) GetColo(ctx context.Context, in *Colo, opts ...grpc.CallOption) (*Colo, error) {
	out := new(Colo)
	err := c.cc.Invoke(ctx, "/stabox.Services/GetColo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesClient) GetServices(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*GetServicesRep, error) {
	out := new(GetServicesRep)
	err := c.cc.Invoke(ctx, "/stabox.Services/getServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicesServer is the server API for Services service.
type ServicesServer interface {
	GetColos(context.Context, *Nothing) (*GetColosRep, error)
	GetColo(context.Context, *Colo) (*Colo, error)
	GetServices(context.Context, *Nothing) (*GetServicesRep, error)
}

// UnimplementedServicesServer can be embedded to have forward compatible implementations.
type UnimplementedServicesServer struct {
}

func (*UnimplementedServicesServer) GetColos(ctx context.Context, req *Nothing) (*GetColosRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetColos not implemented")
}
func (*UnimplementedServicesServer) GetColo(ctx context.Context, req *Colo) (*Colo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetColo not implemented")
}
func (*UnimplementedServicesServer) GetServices(ctx context.Context, req *Nothing) (*GetServicesRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServices not implemented")
}

func RegisterServicesServer(s *grpc.Server, srv ServicesServer) {
	s.RegisterService(&_Services_serviceDesc, srv)
}

func _Services_GetColos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).GetColos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stabox.Services/GetColos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).GetColos(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _Services_GetColo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Colo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).GetColo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stabox.Services/GetColo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).GetColo(ctx, req.(*Colo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Services_GetServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).GetServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stabox.Services/GetServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).GetServices(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

var _Services_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stabox.Services",
	HandlerType: (*ServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getColos",
			Handler:    _Services_GetColos_Handler,
		},
		{
			MethodName: "GetColo",
			Handler:    _Services_GetColo_Handler,
		},
		{
			MethodName: "getServices",
			Handler:    _Services_GetServices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
